Reenable other versions, fixup astropy requirements

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -188,36 +188,36 @@ jobs:
         # Xcookie generates an explicit list of environments that will be used
         # for testing instead of using the more concise matrix notation.
         include:
-        #- python-version: '3.8'
-        #  install-extras: tests-strict,runtime-strict,headless-strict
-        #  os: ubuntu-latest
-        #  arch: auto
-        #  gdal-requirement-txt: requirements/gdal-strict.txt
+        - python-version: '3.8'
+          install-extras: tests-strict,runtime-strict,headless-strict
+          os: ubuntu-latest
+          arch: auto
+          gdal-requirement-txt: requirements/gdal-strict.txt
         - python-version: '3.11'
           install-extras: tests-strict,runtime-strict,optional-strict,headless-strict
           os: ubuntu-latest
           arch: auto
           gdal-requirement-txt: requirements/gdal-strict.txt
-        #- python-version: '3.8'
-        #  install-extras: tests,optional,headless
-        #  os: ubuntu-latest
-        #  arch: auto
-        #  gdal-requirement-txt: requirements/gdal.txt
-        #- python-version: '3.9'
-        #  install-extras: tests,optional,headless
-        #  os: ubuntu-latest
-        #  arch: auto
-        #  gdal-requirement-txt: requirements/gdal.txt
-        #- python-version: '3.10'
-        #  install-extras: tests,optional,headless
-        #  os: ubuntu-latest
-        #  arch: auto
-        #  gdal-requirement-txt: requirements/gdal.txt
-        #- python-version: '3.11'
-        #  install-extras: tests,optional,headless
-        #  os: ubuntu-latest
-        #  arch: auto
-        #  gdal-requirement-txt: requirements/gdal.txt
+        - python-version: '3.8'
+          install-extras: tests,optional,headless
+          os: ubuntu-latest
+          arch: auto
+          gdal-requirement-txt: requirements/gdal.txt
+        - python-version: '3.9'
+          install-extras: tests,optional,headless
+          os: ubuntu-latest
+          arch: auto
+          gdal-requirement-txt: requirements/gdal.txt
+        - python-version: '3.10'
+          install-extras: tests,optional,headless
+          os: ubuntu-latest
+          arch: auto
+          gdal-requirement-txt: requirements/gdal.txt
+        - python-version: '3.11'
+          install-extras: tests,optional,headless
+          os: ubuntu-latest
+          arch: auto
+          gdal-requirement-txt: requirements/gdal.txt
     steps:
     - name: Checkout source
       uses: actions/checkout@v3
@@ -303,7 +303,7 @@ jobs:
   test_deploy:
     name: Uploading Test to PyPi
     runs-on: ubuntu-latest
-    if: github.event_name == 'push' && ! startsWith(github.event.ref, 'refs/tags') && ! startsWith(github.event.ref, 'refs/heads/release') 
+    if: github.event_name == 'push' && ! startsWith(github.event.ref, 'refs/tags') && ! startsWith(github.event.ref, 'refs/heads/release')
     needs:
     - build_and_test_sdist
     - build_binpy_wheels
@@ -323,7 +323,7 @@ jobs:
       env:
         TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
         TWINE_USERNAME: __user__
-        TWINE_PASSWORD: ${{ secrets.PYPY_TEST }}
+        TWINE_PASSWORD: ${{ secrets.PYPI_TEST }}
       run: |-
         pip install urllib3 requests[security] twine -U
         twine upload --username __token__ --password "$TWINE_PASSWORD" --repository-url "$TWINE_REPOSITORY_URL" wheelhouse/* --skip-existing --verbose || { echo "failed to twine upload" ; exit 1; }
@@ -353,6 +353,6 @@ jobs:
         TWINE_PASSWORD: ${{ secrets.PYPI }}
       run: |-
         pip install urllib3 requests[security] twine -U
-        twine upload --username=__token__ --password=$TWINE_PASSWORD --repository-url "$TWINE_REPOSITORY_URL" wheelhouse/* --skip-existing --verbose || { echo "failed to twine upload" ; exit 1; }
+        twine upload --username __token__ --password "$TWINE_PASSWORD" --repository-url "$TWINE_REPOSITORY_URL" wheelhouse/* --skip-existing --verbose || { echo "failed to twine upload" ; exit 1; }
 
 
